# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tutorial Jekyll
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Este blog es el ejemplo de mi tutorial de Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://son-link.github.io/tutorial-jekyll/" # the base hostname & protocol for your site
twitter_username: sonlink
github_username:  son-link

# Build settings
markdown: kramdown

paginate: 1
paginate_path: "page:num/"

gems: [jekyll-paginate]
